[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "binder"
path = "src/binder.rs"


[dependencies]
bytes = "1.0.1"
byteorder = "1.5.0"
prost = "0.12.0"
prost-types = "0.12.0"

[build-dependencies]
prost-build = "0.12.0"
tempfile = "3.8.0"
