codecov:
  require_ci_to_pass: no
  notify:
    # To calculate after_n_builds use
    # ./tools/coverage-tool.py jobs | wc -l
    # also change comment block after_n_builds just below
    after_n_builds: 51
    wait_for_ci: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  after_n_builds: 51

ignore:
  - "src/vendor"
  - "src/proto"

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 0.75%
        if_ci_failed: error #success, failure, error, ignore
    patch:
      default:
        target: 0
        informational: true
      sdk:
        paths:
          - src/sdk/*.py
      sdk-internal:
        paths:
          - src/sdk/internal/
      sdk-launch:
        paths:
          - src/sdk/launch/
      sdk-service:
        paths:
          - src/sdk/service/
      sdk-other:
        paths:
          - "!src/sdk/*.py"
          - "!src/sdk/internal/"
          - "!src/sdk/launch/"
          - "!src/sdk/service/"
          - src/sdk/
      apis:
        informational: true
        paths:
          - src/apis/
      other:
        informational: true
        paths:
          - "!src/sdk/"
          - "!src/apis/"
          - src/

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

github_checks:
  annotations: true
