name: Install Ctrlplane CLI
description: Installs the Ctrlplane CLI binary from a GitHub repository

inputs:
  version:
    description: "Version of the binary to install"
    required: true
  repo:
    description: "GitHub repository containing the binary (format: owner/repo)"
    required: true
    default: "ctrlplanedev/ctrlc"
  url:
    description: "URL of the ctrlplane instance"
    required: false
  api_key:
    description: "API key for the ctrlplane instance"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download binary
      shell: bash
      run: |
        OS=$(uname -s)
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          ARCH="x86_64"
        elif [ "$ARCH" = "aarch64" ]; then
          ARCH="arm64"
        fi

        BINARY_NAME="ctrlc_${OS}_${ARCH}"
        echo "BINARY_NAME: $BINARY_NAME"
        DOWNLOAD_URL="https://github.com/${{ inputs.repo }}/releases/download/${{ inputs.version }}/$BINARY_NAME.tar.gz"

        curl -L $DOWNLOAD_URL -o binary.tar.gz
        tar xzf binary.tar.gz
        chmod +x ${{ inputs.binary }}
        sudo mv ${{ inputs.binary }} /usr/local/bin/

    - name: Set Ctrlplane URL
      shell: bash
      if: inputs.url != ''
      run: |
        ctrlc config set url ${{ inputs.url }}

    - name: Set Ctrlplane API Key
      shell: bash
      if: inputs.api_key != ''
      run: |
        ctrlc config set api-key ${{ inputs.api_key }}
