[version]
path = "wandb/__init__.py"

[build.targets.sdist]
include = [
    "/wandb",
]

[envs.default]
dependencies = [
    "bokeh",
    "boto3",
    "cloudpickle",
    "coverage",
    "docker",
    "fastcore; python_version > '3.6'",
    "fastcore==1.3.29; python_version == '3.6'",
    "google-cloud-aiplatform",
    "google-cloud-storage",
    "hypothesis",
    "imageio",
    "ipykernel",
    "ipython",
    "jax[cpu]; sys_platform == 'darwin' or sys_platform == 'linux'",
    "kfp",
    "kubernetes",
    "lightgbm",
    "matplotlib!=3.5.2",
    "metaflow>=2.3.5",
    "moviepy",
    "nbclient",
    "pandas",
    "Pillow",
    "plotly",
    "prometheus_client",
    "pyarrow",
    "pytest",
    "rdkit-pypi; python_version > '3.7' or sys_platform != 'darwin' or platform.machine != 'arm64'",
    "responses",
    "scikit-learn",
    "soundfile",
    "tensorboard",
    "tensorflow-macos; python_version > '3.6' and python_version < '3.10' and sys_platform == 'darwin' and platform.machine == 'arm64'",
    "tensorflow>=1.15.2; sys_platform != 'darwin' or (python_version > '3.6' and platform.machine != 'arm64')",
    "torch",
    "torchvision",
    "tqdm",
    "xgboost",
]
features = [
    "all",
]

[envs.unit]
dependencies = [
    "parameterized",
    "pytest-cov",
    "pytest-flakefinder",
    "pytest-flask",
    "pytest-mock",
    "pytest-openfiles",
    "pytest-rerunfailures",
    "pytest-split",
    "pytest-timeout",
    "pytest-xdist",
    "pytest",
]

[envs.test]
extra-dependencies = [
    "parameterized",
    "pytest-cov",
    "pytest-flakefinder",
    "pytest-flask",
    "pytest-mock",
    "pytest-openfiles",
    "pytest-rerunfailures",
    "pytest-split",
    "pytest-timeout",
    "pytest-xdist",
    "pytest",
]

[envs.test.scripts]
pytest = "python -m pytest {env:CI_PYTEST_SPLIT_ARGS:} -n={env:CI_PYTEST_PARALLEL:10} --durations=20 --reruns 3 --reruns-delay 1 --junitxml=test-results/junit.xml --cov-config=.coveragerc --cov --cov-report= --no-cov-on-fail {root}/tests/pytest_tests"

[[envs.test.matrix]]
python = ["36", "37", "38", "39", "310"]

[envs.unitshard]
template = "unit"
extra-dependencies = [  # TODO: remove after conftest.py refactor.
    "bokeh",
    "nbclient",
    "matplotlib<3.5.2",
]

[envs.unitshard_nb]
template = "unitshard"
extra-dependencies = [
    "ipykernel",
    "ipython",
    "nbclient",
]

[[envs.unitshard_nb.matrix]]
python = ["36", "37", "38", "39", "310"]

[envs.empty]
detached = true  # Don't require package installation.

[envs.build]
template = "empty"
dependencies = [
    "bumpversion",
    "grpcio-tools>=1.46.3",
    "grpcio>=1.46.3",
    "libcst",
    "twine",
]
