[version]
path = "wandb/__init__.py"

[build.targets.sdist]
include = ["/wandb"]

[envs.default]
# The default environment includes all extras and all dev, build, and test dependencies.
dependencies = [
    "bokeh",
    "boto3",
    "bumpversion",
    "cloudpickle",
    "coverage",
    "docker",
    "fastcore; python_version > '3.6'",
    "fastcore==1.3.29; python_version == '3.6'",
    "google-cloud-aiplatform",
    "google-cloud-storage",
    "grpcio-tools>=1.46.3",
    "grpcio>=1.46.3",
    "hypothesis",
    "imageio",
    "ipykernel",
    "ipython",
    "jax[cpu]; sys_platform == 'darwin' or sys_platform == 'linux'",
    "kfp",
    "kubernetes",
    "libcst",
    "lightgbm",
    "matplotlib!=3.5.2",
    "metaflow>=2.3.5",
    "moviepy",
    "nbclient",
    "pandas",
    "parameterized",
    "Pillow",
    "plotly",
    "prometheus_client",
    "pyarrow",
    "pytest-cov",
    "pytest-flakefinder",
    "pytest-flask",
    "pytest-mock",
    "pytest-openfiles",
    "pytest-rerunfailures",
    "pytest-split",
    "pytest-timeout",
    "pytest-xdist",
    "pytest",
    "rdkit-pypi; python_version > '3.7' or sys_platform != 'darwin' or platform.machine != 'arm64'",
    "responses",
    "scikit-learn",
    "soundfile",
    "tensorboard",
    "tensorflow-macos; python_version > '3.6' and python_version < '3.10' and sys_platform == 'darwin' and platform.machine == 'arm64'",
    "tensorflow>=1.15.2; sys_platform != 'darwin' or (python_version > '3.6' and platform.machine != 'arm64')",
    "torch",
    "torchvision",
    "tqdm",
    "twine",
    "xgboost",
]
features = ["all"]

[envs.unit]
template = "unit" # Don't inherit from the default environment.
dependencies = [
    "parameterized",
    "pytest-cov",
    "pytest-flakefinder",
    "pytest-flask",
    "pytest-mock",
    "pytest-openfiles",
    "pytest-rerunfailures",
    "pytest-split",
    "pytest-timeout",
    "pytest-xdist",
    "pytest",
]

[envs.unitshard]
template = "unit"
extra-dependencies = [ # TODO: remove after conftest.py refactor.
    "bokeh",
    "nbclient",
    "matplotlib!=3.5.2",
]

[envs.test]

[envs.test.env-vars]
PIP_EXTRA_INDEX_URL = "https://download.pytorch.org/whl/cpu"
PIP_TIMEOUT = "600"
COVERAGE_FILE = "{root}/{env_name}/.coverage"
WINDIR = "C:\\Windows"

[envs.test.scripts]
pytest = [
    "- mkdir -p test-results",
    "python -m pytest {env:CI_PYTEST_SPLIT_ARGS:} -n={env:CI_PYTEST_PARALLEL:10} --durations=20 --reruns 3 --reruns-delay 1 --junitxml=test-results/junit.xml --cov-config=.coveragerc --cov --cov-report= --no-cov-on-fail {args:tests/pytest_tests}",
]
cover = [
    "- mkdir -p cover-results",
    "python -m coverage combine {root}/test.py*/.coverage*",
    "coverage xml --ignore-errors",
    "cp .coverage coverage.xml cover-results/",
    "coverage report --ignore-errors --skip-covered --omit \"wandb/vendor/*\"",
    "codecov -e {env_name} -F unittest",
]

[[envs.test.matrix]]
python = ["36", "37", "38", "39", "310"]

[envs.test-launch]
template = "test"
python = "37"

[envs.test-launch.scripts]
pytest = [
    "- mkdir -p test-results",
    "python -m pytest {env:CI_PYTEST_SPLIT_ARGS:} -n={env:CI_PYTEST_PARALLEL:4} --durations=20 --reruns 3 --reruns-delay 1 --junitxml=test-results/junit.xml --cov-config=.coveragerc --cov --cov-report= --no-cov-on-fail {args:tests/pytest_tests/unit_tests_old/tests_launch/}",
]

[envs.unit-s_nb]
template = "unitshard"
extra-dependencies = ["ipykernel", "ipython", "nbclient"]

[envs.unit-s_nb.env-vars]
COVERAGE_FILE = "{root}/{env_name}/.coverage"
WINDIR = "C:\\Windows"
WB_UNIT_SHARD = "s_nb"

[envs.unit-s_nb.scripts]
pytest = [
    "- mkdir -p test-results",
    "ipython kernel install --user --name=wandb_python",
    "python -m pytest {env:CI_PYTEST_SPLIT_ARGS:} -n={env:CI_PYTEST_PARALLEL:{env:WB_UNIT_PARALLEL:4}} --durations=20 --reruns 3 --reruns-delay 1 --junitxml=test-results/junit.xml --cov-config=.coveragerc --cov --cov-report= --no-cov-on-fail --timeout 300 {args:tests/pytest_tests/unit_tests_old/tests_{env:WB_UNIT_SHARD}/}",
]

[[envs.unit-s_nb.matrix]]
python = ["36", "37", "38", "39", "310"]


[envs.func-s]
extra-dependencies = ["coverage", "yea-wandb{env:YEA_WANDB_VERSION:}"]

[envs.func-s.env-vars]
YEA_WANDB_VERSION = "==0.9.5"
WANDB__NETWORK_BUFFER = "1000"  # Low network buffer to exercise flow control logic.
COVERAGE_FILE="{root}/.coverage"
YEACOV_SOURCE="{root}/wandb/"
# s_kfp: WB_PROBE_PACKAGE=true

[envs.func-s.scripts]
pytest = [
    "- mkdir -p test-results",
    "yea {env:CI_PYTEST_SPLIT_ARGS:} --strict --shard {matrix:shard:default} run {args:--all}",
]
cover = [
    "- mkdir -p cover-results",
    "python -m coverage combine {root}/func-s*.py*/.coverage*",
    "python -m coverage xml --ignore-errors",
    "cp .coverage coverage.xml cover-results/",
    "coverage report --ignore-errors --skip-covered --omit \"wandb/vendor/*\"",
    "codecov -e {env_name} -F functest",
]

[[envs.func-s.matrix]]
python = ["36", "37", "38", "39", "310"]
shard = [
    "default",
    "sklearn",
    "metaflow",
    "tf115",
    "tf21",
    "tf24",
    "tf25",
    "tf26",
    "ray112",
    "ray2",
    "service",
    "grpc",
    "py310",
    "imports1",
    "imports2",
    "imports3",
    "imports4",
    "imports5",
    "imports6",
    "imports7",
    "imports8",
    "imports9",
    "imports10",
    "imports11",
    "imports12",
    "noml",
]

[envs.func-s_docs]
template = "func-s"

[envs.func-s_docs.scripts]
pytest = [
    "- mkdir -p test-results",
    "yea {env:CI_PYTEST_SPLIT_ARGS:} --strict --yeadoc --shard docs run {args:--all}",
]

[[envs.func-s_docs.matrix]]
python = ["36", "37", "38", "39", "310"]

[envs.func-s_kfp]
template = "func-s"
python = ["37"]

[envs.func-s_kfp.scripts]
pytest = [
    "- mkdir -p test-results",
    "yea {env:CI_PYTEST_SPLIT_ARGS:} --strict -p wandb:mockserver-bind=0.0.0.0 -p wandb:mockserver-host=__auto__ --shard kfp run {posargs:--all}",
]


[envs.empty]
detached = true # Don't require package installation.

[envs.build]
template = "empty"
dependencies = [
    "bumpversion",
    "grpcio-tools>=1.46.3",
    "grpcio>=1.46.3",
    "libcst",
    "twine",
]
