# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: ctrlclient
output: internal/ctrlclient/client.gen.go
generate:
  models: true
  client: true
