[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
src/vendor/
| src/bin/
| src/proto/
| src/proto_check/
| src/sdk/launch/deploys/
| wandb/run*
| wandb/offline-run*
| __pycache__
| .pyc
| .tox/
'''

[tool.isort]
profile = "black"
skip = ["src/__init__.py"]
extend_skip_glob = ["src/vendor/**", "src/proto/**"]
skip_gitignore = "True"
