apiVersion: v1
kind: Namespace
metadata:
  name: wandb
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
---
# role for handling builds and jobs within the wandb namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wandb
  name: wandb-launch-agent
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "pods/log"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
---
# cluster role to creating ML jobs in desired namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wandb-launch-serviceaccount
  namespace: wandb
---
# role binding for namespaced role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-role-binding
  namespace: wandb
subjects:
- kind: ServiceAccount
  name: wandb-launch-serviceaccount
  namespace: wandb
roleRef:
  kind: Role
  name: wandb-launch-agent
  apiGroup: rbac.authorization.k8s.io
---
# role binding to create ML jobs in another namespace (could use cluster role binding if we want to launch cluster wide)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-cluster-role-binding
  namespace: default #TODO: SET YOUR TRAINING NAMESPACE
subjects:
- kind: ServiceAccount
  name: wandb-launch-serviceaccount
  namespace: wandb
roleRef:
  kind: ClusterRole
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  launch-config.yaml: |
    base_url: https://api.wandb.ai # TODO: SET YOUR WANDB BASE URL
    project: pluto # TODO: SET YOUR ML PROJECT
    entity: drc-test
    max_jobs: -1 # TODO: SET YOUR MAX CONCURRENT JOBS HERE
    registry:
      url: 305054156030.dkr.ecr.us-east-2.amazonaws.com/launch-jupyter # TODO: SET ECR REPOSITORY URL HERE
      ecr-provider: AWS # TODO: SET ECR PROVIDER HERE
      credentials:
        secret-name: aws-secret # TODO: SET SECRET NAME HERE
        secret-mount-path: /root/.aws # SET MOUNT PATH HERE for aws /root/.aws
      config:
        secret-name: aws-config
        secret-mount-path: /root/.aws
    build:
      type: kaniko
      cloud-provider: AWS # TODO: SET CLOUD PROVIDER HERE
      credentials:
        secret-name: aws-secret
        secret-mount-path: /root/.aws
      config:
        secret-name: aws-config
        secret-mount-path: /root/.aws
      build-context-store: wandb-build-griffin # name here
    runner:
      type: kubernetes
      namespace: wandb # TODO: set namespace here

kind: ConfigMap
metadata:
  name: wandb-launch-configmap
  namespace: wandb
---
apiVersion: v1
kind: Secret
metadata:
  name: wandb-api-key
  namespace: wandb
type: kubernetes.io/basic-auth
stringData:
  password: "40d97fb6a5c31c011bf2f5ba2d47b0943a00ebf9"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jupyter-test-pod

# spec:
#   clusterIP: None
#   selector:
#     app: jupyter-test-pod
#     environment: test
#   ports:
#   - protocol: TCP
#     port: 8888
#     targetPort: 8888
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: jupyter-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: "nginx"
#     ingress.kubernetes.io/force-ssl-redirect: "true"
#     ingress.kubernetes.io/proxy-body-size: "800m"
#     nginx.ingress.kubernetes.io/proxy-body-size: "800m"
#     certmanager.k8s.io/issuer: "letsencrypt-prod"

# spec:
#   # tls:
#   # # - hosts:
#   # #   - jupyter.example.com
#   # #   # secretName: jupyter-tls
#   rules:
#   # - host: jupyter.example.com
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: jupyter-test-pod
#             port: 
#               number: 8888
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  defaultBackend:
    service:
      name: jupyter
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: jupyter
  name: jupyter
spec:
  ports:
  - name: "80"
    port: 8888
    targetPort: 80
  selector:
    name: jupyter
  type: NodePort