name: Install Ctrlplane CLI
description: Installs the Ctrlplane CLI binary from a GitHub repository

inputs:
  version:
    description: "Version of the binary to install"
    required: false
    default: "latest"
  repo:
    description: "GitHub repository containing the binary (format: owner/repo)"
    required: false
    default: "ctrlplanedev/cli"
  resource_id:
    description: "ID of the resource to get"
    required: true
  url:
    description: "URL of the ctrlplane instance"
    required: false
  api_key:
    description: "API key for the ctrlplane instance"
    required: false
  required_outputs:
    description: "Required outputs"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: ctrlplanedev/cli@main
      with:
        version: ${{ inputs.version }}
        repo: ${{ inputs.repo }}
        url: ${{ inputs.url }}
        api_key: ${{ inputs.api_key }}

    - name: Set Object Outputs
      shell: bash
      run: |
        RESOURCE=$(ctrlc api get resource --id ${{ inputs.resource_id }})

        echo "resource=$RESOURCE" >> "$GITHUB_OUTPUT"

        # Extract flattened key-value pairs and write to output
        echo "$RESOURCE" | jq -r 'paths(scalars) as $p | [ ( [ $p[] | tostring ] | join("_") ), ( getpath($p) | tostring ) ] | join("=")' | while read -r line; do
            echo "$line" >> "$GITHUB_OUTPUT"
            echo "$line"
        done

        echo "${{ inputs.required_outputs }}" | while read -r output; do
            if [ ! -z "$output" ]; then
                echo "Checking for output: $output"
                if ! grep -q "^$output=" $GITHUB_OUTPUT; then
                    echo "Required output \"$output\" not found in outputs."
                    exit 1
                fi
            fi
        done
