version: 2.1

orbs:
  slack: circleci/slack@4.12.5

parameters:
  python_version:
    description: "Python version"
    type: string
    default: "3.8"
  go_version:
    description: "Go version"
    type: string
    default: "1.21.4"

commands:
  install_go:
    description: "Install Go with the specified version and system"
    parameters:
      version:
        description: "Go version"
        type: string
        default: << pipeline.parameters.go_version >>
    steps:
      - run:
          name: Install Go
          command: |
            system=$(uname -s | tr '[:upper:]' '[:lower:]')
            if [ "$system" = "darwin" ]; then
              system="darwin-amd64"
            else
              system="linux-amd64"
            fi
            wget https://go.dev/dl/go<<parameters.version>>.$system.tar.gz
            tar -C . -xzf go<<parameters.version>>.$system.tar.gz
            rm go<<parameters.version>>.${system}.tar.gz
            echo 'export PATH="go/bin:$PATH"' >> "$BASH_ENV"
          no_output_timeout: 1m


executors:
  test-server:
    docker:
      - image: cimg/python:<< parameters.python_version >>
      - image: us-central1-docker.pkg.dev/wandb-production/images/local-testcontainer:<< parameters.server_tag >>
        auth:
          username: _json_key
          password: $GCP_SERVICE_ACCOUNT_JSON_DECODED
        environment:
          CI: 1
          WANDB_ENABLE_TEST_CONTAINER: true
    parameters:
      python_version:
        description: "Python version"
        type: string
      server_tag:
        description: "Test server repository tag"
        type: string
        default: master
    resource_class: xlarge
    working_directory: /mnt/ramdisk

jobs:
  test:
    description: "Run tests against test server"
    parameters:
      python_version:
        description: "Python version"
        type: string
        default: << pipeline.parameters.python_version >>
    executor:
      name: test-server
      python_version: << parameters.python_version >>
    steps:
      - checkout
      - install_go
      - run:
          name: Check Python version
          command: |
            python --version
            go version
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@channel"
          channel: $SLACK_SDK_NIGHTLY_CI_CHANNEL


workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
               python_version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
