name: Generate Documentation

env:
  # share an ssh-agent socket across jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  push

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: wandb/docugen@debug-ref-docs
        with:
          client-branch: debug-ref-docs
          gitbook-branch: debug
          access-token: ${{ secrets.DOCUGEN_ACCESS_TOKEN }}
