name: Generate Documentation

env:
  # share an ssh-agent socket across jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on: # Whenever a release is published,
  push
  #release:
  #  types: [published]

jobs: # update the docs.
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: wandb/docugen@debug-ref-docs
        with:
          gitbook-branch: debug
          access-token: ${{ secrets.DOCUGEN_ACCESS_TOKEN }}
