# GitHub Action that runs on windows and uses hello world docker image as a service
name: unit-s_base-win
on:
  push:
    branches:
      - master
  pull_request:
jobs:
    unit-s_base-win-py37:
      runs-on: windows-latest
      services:
        wandb:
          image: wandb/local:latest
          ports:
            - "8080:8080"
      env:
        WANDB_BASE_URL: "http://localhost:8080"
      timeout-minutes: 20
      strategy:
        matrix:
          python-version:
            - '3.7'
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        - name: Run Windows Unit Tests
          run: |
            python -m pip install --upgrade pip
            pip install wheel
            pip install -e .
            curl -L http://localhost:8080/healthz
